"""empty message

Revision ID: 420554b5dbb1
Revises: 1a7b65c74688
Create Date: 2023-03-30 21:33:49.358235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '420554b5dbb1'
down_revision = '1a7b65c74688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('edited')
        batch_op.drop_column('created')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('edited', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
